# Generated by Django 5.2.7 on 2025-11-07 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_productgallery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productgallery',
            options={'verbose_name': 'productgallery', 'verbose_name_plural': 'productgallery'},
        ),
    ]
